### ISSUE TITLE
waiting for your stage3 code

### ISSUE THREAD

**Issue by liberty-hit** [cvlab-yonsei/BANA#2]

**Comment by wuzhenyubuaa** [comment]
Hi, may I ask you a question? could you find the BgMaskfromBoxes fold?
![1634625538](https://user-images.githubusercontent.com/40664663/137856894-ac436f5a-f204-45b1-8131-a8fbbe1c5318.png)

**Comment by Aoldcat1997** [comment]
> Hi, may I ask you a question? could you find the BgMaskfromBoxes fold? ![1634625538](https://user-images.githubusercontent.com/40664663/137856894-ac436f5a-f204-45b1-8131-a8fbbe1c5318.png)
the BgMaskfromBoxes fold is in markdowd,you can download from the author's google driver

**Comment by 50min** [comment]
We attached stage3_vgg.py which includes the code to compute NAL.

We hope this helps.
