### ISSUE TITLE
Where is  BgMaskformBoxes ?

### ISSUE THREAD

**Issue by wuzhenyubuaa** [cvlab-yonsei/BANA#3]
![1634625238(1)](https://user-images.githubusercontent.com/40664663/137856097-d23c9ddb-2ffd-4c25-b09d-338959fb219b.png)
Hi, I am a newer for semantic segmentation, I can't find the BgMaskformBoxes. Somebody knows that ?

**Comment by whiterAutumn** [comment]
hello, have you solved this problem? I look forward to knowing how to generate it as well。

**Comment by wuzhenyubuaa** [comment]
I have no idea about that



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2021年12月21日 17:30 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [cvlab-yonsei/BANA] Where is BgMaskformBoxes ? (Issue #3) |

hello, have you solved this problem? I look forward to knowing how to generate it as well。

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by whiterAutumn** [comment]
Literally, is it the area in the bound box other than the target ROI？This is surmise on my part！ @50min

**Comment by 50min** [comment]
Dear @wuzhenyubuaa and @whiterAutumn,
We generated binary masks for all training images by using ground-truth bounding boxes, and saved them in the repository called 'BgMaskfromBoxes'. In this way, we aim to make the implementations such as the data augmentation process easy, when training the classification network. Kindly note that the number of all training images is 10,582.

We attached the download link for 'BgMaskfromBoxes', please check it out.

We hope this helps.

**Comment by whiterAutumn** [comment]
Thank you very much. @50min
